import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { signIn, signOut, useSession } from 'next-auth/react';

import { api } from '../utils/api';
import MainApp from '../components/layouts/MainApp';
import ProtectedRoutes from '../components/layouts/ProtectedRoutes';
import styles from '../styles/dividers.module.css';
import classNames from 'classnames';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta
					name='description'
					content='Generated by create-t3-app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<ProtectedRoutes>
				<MainApp>
					<SectionContentContainer classname='relative flex h-screen flex-col items-center bg-blue-500 text-beige-500 md:p-[20vw]'>
						<div className='z-10 ml-4 mt-20 flex flex-col'>
							<h2 className='relative animate-pulse text-xl'>
								What Todo?
							</h2>
							<p className=''>
								Lorem ipsum dolor sit amet consectetur
								adipisicing elit. Officiis possimus dolore sed
								quidem deserunt delectus atque quibusdam earum
								accusantium sit officia, ad expedita nihil
								obcaecati quas placeat voluptatem enim
								explicabo?
							</p>
						</div>
						<div className={classNames(styles.divider1, '')}>
							<svg
								data-name='Layer 1'
								xmlns='http://www.w3.org/2000/svg'
								viewBox='0 0 1200 120'
								preserveAspectRatio='none'
								className='fill-beige-500'
							>
								<path d='M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z'></path>
							</svg>
						</div>
						<div className={styles.divider2}>
							<svg
								data-name='Layer 1'
								xmlns='http://www.w3.org/2000/svg'
								viewBox='0 0 1200 120'
								preserveAspectRatio='none'
								className='fill-beige-500'
							>
								<path
									d='M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z'
									className=''
								></path>
							</svg>
						</div>
					</SectionContentContainer>
					<SectionContentContainer classname='flex-col items-center bg-beige-500 p-[20vw] text-blue-500'>
						<h2>Hello Sej</h2>
						<p>
							Numquam exercitationem voluptas sapiente saepe
							laborum harum, a necessitatibus, molestias maxime
							officiis neque corrupti mollitia suscipit cum
							quisquam alias consequatur autem quasi beatae
							laboriosam? Ducimus, at repudiandae! Provident,
							facilis error!
						</p>
					</SectionContentContainer>
					<SectionContentContainer classname='relative flex h-screen flex-col bg-blue-500 text-beige-500'>
						<div className='flex w-full gap-4'>
							<h2 className=''>About the Developer</h2>
							<p className='line-clamp-4'>
								Veritatis vero impedit magni! Numquam,
								reiciendis optio deleniti minus, architecto
								nemo corrupti pariatur velit mollitia veniam
								neque. Quam facere natus amet repellat hic, in
								cumque laboriosam. Perferendis provident nisi
								obcaecati.
							</p>
						</div>
					</SectionContentContainer>
				</MainApp>
			</ProtectedRoutes>
		</>
	);
};

export default Home;

const SectionContentContainer = ({
	children,
	classname,
}: {
	children?: React.ReactNode;
	classname?: string;
}) => {
	return (
		<section
			className={classNames(
				'relative flex h-screen w-full',
				classname
			)}
		>
			{children}
		</section>
	);
};
